# Generated by Django 2.2.7 on 2019-11-09 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.Artwork'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='likes',
            field=models.ManyToManyField(related_name='Liker', through='picture.Like', to='user.User'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('artwork', 'user')},
        ),
    ]
