# Generated by Django 2.2.7 on 2019-11-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_auto_20191109_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='price',
            field=models.IntegerField(default=20, max_length=1000),
        ),
    ]
