# Generated by Django 2.2.7 on 2019-11-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_artwork_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
    ]
